main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

makanan/urls.py
from django.contrib import admin
from django.urls import path, include
from makanan import views

urlpatterns = [
    path('<int:makanan_id>/', views.detail_makanan, name="detail"),
    path('<int:makanan_id>/edit', views.edit_makanan, name='edit'),
    path('<int:makanan_id>/main', views.show_makanan, name='main')
]

pacil_food/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('main.urls', 'main'), namespace='main')),
    path('u/', include(('user_profile.urls', 'user_profile'), namespace='user-profile')),
    path('toko/', include(('toko.urls', 'toko'), namespace='toko')),
    path('makanan/', include(('makanan.urls', 'makanan'), namespace='makanan')),
    path('keranjang/', include(('keranjang.urls', 'keranjang'), namespace='keranjang')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('review/', include(('review.urls', 'review'), namespace='review')),
    path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
    ]

review/urls.py
from django.urls import path
from review.views import show_review, reply_review, create_review

appname = 'review'

urlpatterns = [
    path('<int:makanan_id>/', show_review, name='show_review'),
    path('create/<int:makanan_id>/', create_review, name='create_review'),
    path('reply/<int:review_id>/', reply_review, name='reply_review')
]

toko/urls.py
from django.urls import path
from toko import views


urlpatterns = [
    path('<int:toko_id>', views.info_toko, name='info_toko'),
    path('manage', views.manage_toko, name='manage'),
    path('manage/<int:toko_id>', views.manage_toko, name='manage'),
    path('create', views.create_toko, name='create_toko'),
    path('<int:toko_id>/tambah-makanan', views.tambah_makanan, name='tambah_makanan'),
]

makanan/models.py
from django.core.validators import MinValueValidator
from django.db import models

from toko.models import Toko


class Makanan(models.Model):
    nama = models.CharField(max_length=250)
    harga = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
    stok = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    toko = models.ForeignKey(Toko, on_delete=models.CASCADE)
    img_url = models.CharField(max_length=500)

makanan/forms.py
from django.forms import ModelForm, ChoiceField
from makanan.models import Makanan


class MakananForm(ModelForm):

    class Meta:
        model = Makanan
        fields = ['nama', 'harga', 'stok', 'img_url']

makanan/views.py
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import render, redirect
from makanan.models import Makanan
from review.models import Review
from toko.models import Toko
from makanan.forms import MakananForm
from django.http import HttpResponseRedirect
from django.urls import reverse


def detail_makanan(request, makanan_id):
    makanan = Makanan.objects.get(pk=makanan_id)
    reviews = Review.objects.filter(makanan=makanan)
    is_penjual = False

    try:
        toko = Toko.objects.get(user=request.user)
        if toko == makanan.toko:
            is_penjual = True
    except Toko.DoesNotExist:
        pass

    rating = 0
    count = 0

    for review in reviews:
        rating += review.nilai
        count += 1

    if count != 0:
        rating /= count

    context = {
        'makanan': makanan,
        'reviews': reviews,
        'rating': rating,
        'is_penjual': is_penjual
    }

    return render(request, "detail_makanan.html", context)


def get_stok(request):
    makanan = Makanan.objects.get(pk=request.GET.get('makanan_id'))
    return render(request, 'get_stok.html', {'makanan': makanan})


def show_makanan(request):
    makanan = Makanan.objects.all()

    context = {
        'name': request.user.username,
        'makanan': makanan

    }

    return render(request, 'main_makanan.html', context)


def delete_makanan(request, makanan_id):
    makanan = Makanan.objects.get(pk=makanan_id)
    makanan.delete()
    return HttpResponseRedirect(reverse('main:index'))


def edit_makanan(request, makanan_id):
    makanan = Makanan.objects.get(pk=makanan_id)

    form = MakananForm(request.POST or None, instance=makanan)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('makanan:detail', args=[makanan.id]))

    context = {'form': form}
    return render(request, "edit_makanan.html", context)

makanan/templates/detail_makanan.html
{% extends 'base.html' %}

{% block meta %}
    <title>Detail Makanan</title>
{% endblock meta %}

{% block content %}
    <div class="w-full min-h-screen flex py-12 px-20 flex-col gap-16">
        <div class="w-full h-[50vh] flex h-fit">
            <section class="basis-1/3">
                <figure class="aspect-square rounded-xl overflow-hidden">
                    <img src="{{ makanan.img_url }}" alt="" class="h-full object-cover object-center">
                </figure>
            </section>
            <section class="basis-2/3 px-12 py-2 flex flex-col">
                <h2 class="text-5xl font-semibold">{{ makanan.nama }}</h2>
                <div class="text-1xl font-thin">
                    <i class="fa-solid fa-star"></i>
                    <span>({{ rating|floatformat:1 }})</span>
                </div>

                <h3 class="text-2xl font-bold mt-5">Rp{{ makanan.harga }}</h3>
                <div class="card mt-5">
                    <div class="card-body flex-row bg-primary px-5 py-3 max-w-xs text-primary-content justify-between items-center rounded-xl">
                        <h5 class="">{{ makanan.toko.name }}</h5>
                        <a href="{% url 'toko:info_toko' toko_id=makanan.toko.pk %}" class="btn btn-secondary">Kunjungi Toko</a>
                    </div>
                </div>
                <p class="mt-5 text-lg">{{ makanan.deskripsi }}</p>
                {% if is_penjual == True %}
                    <a href="{% url 'makanan:edit' makanan_id=makanan.pk %}" class="btn btn-primary max-w-xs mt-5 self-end"                                                                 `                                                                                       aria-required="false"                                                                                                                                               a>
                        Edit Makanan
                    </a>
                {% else %}
                    <button class="btn btn-primary max-w-xs mt-5 self-end" value="{{ makanan.pk }}" onclick="addToCart(this)">
                        Tambahkan ke Keranjang
                    </button>
                {% endif %}
            </section>
        </div>
        <div class="">
            <h3 class="text-xl font-bold">Reviews</h3>
            <div>
                {% for review in reviews %}
                    <div class="mb-5 mt-5">
                        <div class="card bg-secondary">
                            <div class="card-body">
                                <h5 class="card-title">{{ review.user }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Rating: {{ review.nilai }}</h6>
                                <div class="stars" data-nilai="{{ review.nilai }}" style="font-size: 24px;">
                                </div>
                                <p class="card-text">Komentar: {{ review.komentar }}</p>
                                {% if review.reply %}
                                <p class="card-text"><small class="text-muted">Reply: {{ review.reply }}</small></p>
                                {% else %}
                                <p class="card-text"><small class="text-muted">Penjual belum memberikan balasan</small></p>
                                {% if user.profile.role == 'penjual' and toko.pk == review.makanan.toko.pk %}
                                    <a href="{% url 'review:reply_review' review.pk %}" class="btn btn-primary">Balas</a>
                                {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

makanan/templates/edit_makanan.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Makanan</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Makanan"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

makanan/templates/tambah_makanan.html
{% extends 'base.html' %}

{% block meta %}
    <title>Tambah Makanan Baru</title>
{% endblock meta %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td>
          <input type="submit" value="Tambah Makanan Baru" />
        </td>
      </tr>
    </table>
  </form>
  
  
  {% endblock content %}