keranjang/urls.py
from django.urls import path
from keranjang import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.show_main, name='show-main'),
    path('get-item/', views.get_item, name='get-item'),
    path('add-item', views.add_item, name='add-item'),
    path('delete-item/<int:keranjang_id>', views.delete_item, name='delete-item'),
    path('checkout-cart/', views.checkout_cart, name='checkout-cart'),
    path('cek-stok/<int:keranjang_id>', views.cek_stok, name='cek-stok'),
    path('update-jumlah/<int:keranjang_id>', views.update_jumlah, name='update-jumlah')
]

main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path
from order.views import show_main_penjual, show_main_pembeli, edit_status_penjual, edit_status_batal

app_name = 'order'

urlpatterns = [
    path('toko/<int:toko_id>', show_main_penjual, name='show_main_penjual'),
    path('', show_main_pembeli, name='show_main_pembeli'),
    path('edit_status_penjual/', edit_status_penjual, name='edit_status_penjual'),
    path('edit_status_batal/<int:og_id>', edit_status_batal, name='edit_status_batal'),
]

pacil_food/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('main.urls', 'main'), namespace='main')),
    path('u/', include(('user_profile.urls', 'user_profile'), namespace='user-profile')),
    path('toko/', include(('toko.urls', 'toko'), namespace='toko')),
    path('makanan/', include(('makanan.urls', 'makanan'), namespace='makanan')),
    path('keranjang/', include(('keranjang.urls', 'keranjang'), namespace='keranjang')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('review/', include(('review.urls', 'review'), namespace='review')),
    path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
    ]

keranjang/models.py
from django.db import models
from django.contrib.auth.models import User
from makanan.models import Makanan


class ItemKeranjang(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    makanan = models.ForeignKey(Makanan, on_delete=models.CASCADE)
    jumlah = models.IntegerField(default=1)

keranjang/views.py
from django.core import serializers
from django.http import HttpResponseNotFound, HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import json

from keranjang.models import ItemKeranjang
from makanan.models import Makanan
from order.models import OrderGroup, Order
from django.contrib.auth.decorators import login_required


@login_required()
def show_main(request):
    cart = ItemKeranjang.objects.all()

    print(cart)

    context = {
        'cart': cart,
    }

    return render(request, "home.html", context)


def get_item(request):
    items = ItemKeranjang.objects.filter(user=request.user)

    return HttpResponse(serializers.serialize('json', items), content_type='application/json')


@csrf_exempt
def add_item(request):
    if request.method == 'POST':
        makanan_id = request.POST.get("makanan_id")
        makanan = Makanan.objects.get(pk=int(makanan_id))
        user = request.user

        try:
            item = ItemKeranjang.objects.get(makanan=makanan)

            if item.jumlah >= item.makanan.stok:
                return HttpResponse(status=400)

            item.jumlah = item.jumlah + 1
            item.save()
        except ItemKeranjang.DoesNotExist:
            new_item = ItemKeranjang(makanan=makanan, user=user)
            new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


@csrf_exempt
def delete_item(request, keranjang_id):

    ItemKeranjang.objects.get(pk=keranjang_id).delete()

    return HttpResponse(b"DELETED", status=200)


def cek_stok(request, keranjang_id):
    keranjang = ItemKeranjang.objects.get(pk=keranjang_id)
    stok = keranjang.makanan.stok
    return JsonResponse({'stok': stok})


@csrf_exempt
def checkout_cart(request):
    if request.method == 'POST':
        ids = json.loads(request.POST.get('obj'))
        total_harga = request.POST.get('total')

        order_group = OrderGroup(user=request.user, total_harga=total_harga)
        order_group.save()

        for item_id in ids:
            item = ItemKeranjang.objects.get(pk=int(item_id))

            if item.jumlah > item.makanan.stok:
                order_group.delete()
                return HttpResponse(400)

            order = Order(order_group=order_group, user=request.user, makanan=item.makanan, toko=item.makanan.toko, quantity=item.jumlah)
            order.save()

            item.makanan.stok -= item.jumlah
            item.makanan.save()

            item.delete()

        return JsonResponse({'message': 'Checkout successful'})

    return HttpResponseNotFound()


@csrf_exempt
def update_jumlah(request, keranjang_id):

    if request.method == "POST":
        keranjang = ItemKeranjang.objects.get(pk=keranjang_id)
        keranjang.jumlah = request.POST.get('jumlah')
        keranjang.save()

        return JsonResponse({'jumlah': keranjang.jumlah})

    return HttpResponseNotFound()

keranjang/templates/home.html
{% extends 'base.html' %}

{% block meta %}
    <title>Cart</title>
{% endblock meta %}

{% block content %}
    <div class="w-full min-h-screen">
        <div class="w-full px-10">
            <form id="cart-form" method="POST">
                <table class="table table-fixed">
                    <!-- head -->
                    <thead>
                    <tr>
                        <th></th>
                        <th>Menu</th>
                        <th>Harga</th>
                        <th>Quantity</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% csrf_token %}
                    {% for item in cart %}
                        <tr id="cart-row-{{ item.pk }}" class="hover">
                            <th class="flex justify-center">
                                <label>
                                    <input type="checkbox" class="cb-checkout checkbox" onchange="checkedButton(this)"
                                           value="{{ item.pk }}" name="cart-item-{{ item.pk }}"/>
                                </label>
                            </th>
                            <td>
                                <div class="flex items-center gap-3">
                                    <div class="avatar">
                                        <div class="mask mask-squircle w-12 h-12">
                                            <img src="/tailwind-css-component-profile-2@56w.png"
                                                 alt="Avatar Tailwind CSS Component"/>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="font-bold">{{ item.makanan.nama }}</div>
                                        <div class="text-sm opacity-50">{{ item.makanan.toko }}</div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                {{ item.makanan.harga }}
                                <br/>
                                <span class="badge badge-ghost badge-sm">{{ item.makanan.kategori }}</span>
                            </td>
                            <th class="join">
                                <button class="btn join-item" type="button" onclick="decreaseQuantity(this)"
                                        value="{{ item.pk }}">-
                                </button>
                                <div>
                                    <input class="input w-14 join-item" disabled type="text" id="quantity-{{ item.pk }}"
                                           value="{{ item.jumlah }}" min="1"/>
                                </div>
                                <button class="btn join-item" type="button" onclick="increaseQuantity(this)"
                                        value="{{ item.pk }}">+
                                </button>
                            </th>
                            <th>
                                <button
                                        onclick="deleteItem(this.value)"
                                        type="button"
                                        value="{{ item.pk }}"
                                        class="btn flex justify-center items-center btn-square bg-transparent border-transparent"
                                >
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </th>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="flex items-center float-end w-1/3 mt-5 mr-16 gap-10">
                    <div class="flex flex-col">
                        <span class="text-sm">Total:</span>
                        <span id="total-price" class="font-bold text-xl">$0</span>
                    </div>
                    <button type="button" onclick="submitForm()" class="btn btn-primary grow rounded-full">
                        Checkout
                    </button>
                </div>
            </form>
            <dialog id="kelebihan_alert" class="modal">
                <div class="modal-box">
                    <h3 class="font-bold text-lg">Peringatan</h3>
                    <p class="py-4">Stok makanan tidak mencukupi</p>
                    <div class="modal-action">
                        <form method="dialog">
                            <!-- if there is a button in form, it will close the modal -->
                            <button class="btn">Close</button>
                        </form>
                    </div>
                </div>
            </dialog>
        </div>
    </div>
    <script>
        const daftarKeranjang = {}
        let hargaTotal = 0
        const hargaElement = document.getElementById('total-price')

        {% for item in cart %}
            daftarKeranjang["{{ item.pk }}"] = {};

            daftarKeranjang["{{ item.pk }}"]['stok'] = {{ item.makanan.stok }}
            daftarKeranjang["{{ item.pk }}"]['harga'] = {{ item.makanan.harga }}
            daftarKeranjang["{{ item.pk }}"]['jumlah'] = {{ item.jumlah }}
            daftarKeranjang["{{ item.pk }}"]['check'] = false
        {% endfor %}

        function hitungTotalHarga() {
            hargaTotal = 0
            for (let item in daftarKeranjang) {
                if (daftarKeranjang[item]['check']) {
                    hargaTotal += daftarKeranjang[item]['harga'] * daftarKeranjang[item]['jumlah']
                }
            }
        }

        async function updateHarga() {
            hitungTotalHarga()

            hargaElement.innerText = `${hargaTotal}`
        }

        async function checkedButton(el) {
            daftarKeranjang[el.value]['check'] = el.checked
            await updateHarga()
        }

        updateHarga()

        async function deleteItem(id) {
            // 9999 is only a placeholder
            await fetch(`{% url 'keranjang:delete-item' keranjang_id=9999 %}`.replace(/9999/, id), {
                method: "DELETE"
            })

            document.getElementById(`cart-row-${id}`).remove()
            delete daftarStok[id]
        }

        async function updateJumlah(id, quantity) {
            var data = new FormData()
            data.append('jumlah', quantity.toString())

            await fetch("{% url 'keranjang:update-jumlah' keranjang_id=9999 %}".replace(/9999/, id), {
                method: "POST",
                body: data
            })
        }

        async function decreaseQuantity(el) {
            let quantityInput = document.getElementById(`quantity-${el.value}`);
            let quantity = Number(quantityInput.value);
            if (quantity > 1) {
                quantityInput.value = quantity - 1;
                daftarKeranjang[el.value]['jumlah'] = quantity - 1;

                await updateJumlah(el.value, quantity - 1)

                updateHarga()
            }
        }

        async function increaseQuantity(el) {
            let quantityInput = document.getElementById(`quantity-${el.value}`);
            let quantity = Number(quantityInput.value);

            if (quantity >= daftarKeranjang[el.value]['stok']) {
                kelebihan_alert.showModal();
                return
            }

            quantityInput.value = quantity + 1;
            daftarKeranjang[el.value]['jumlah'] = quantity + 1;

            await updateJumlah(el.value, quantity + 1)

            updateHarga()
        }

        async function submitForm() {
            var data = new FormData()

            const items = []

            for (const item in daftarKeranjang) {
                if (daftarKeranjang[item]['check']) {
                    items.push(item)
                }
            }

            data.append('obj', JSON.stringify(items))
            data.append('total', hargaTotal.toString())

            await fetch("{% url 'keranjang:checkout-cart' %}", {
                method: "POST",
                body: data
            })

            window.location.replace("{% url 'order:show_main_pembeli' %}");
        }
    </script>
{% endblock content %}