main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path
from order.views import show_main_penjual, show_main_pembeli, edit_status_penjual, edit_status_batal

app_name = 'order'

urlpatterns = [
    path('toko/<int:toko_id>', show_main_penjual, name='show_main_penjual'),
    path('', show_main_pembeli, name='show_main_pembeli'),
    path('edit_status_penjual/', edit_status_penjual, name='edit_status_penjual'),
    path('edit_status_batal/<int:og_id>', edit_status_batal, name='edit_status_batal'),
]

pacil_food/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('main.urls', 'main'), namespace='main')),
    path('u/', include(('user_profile.urls', 'user_profile'), namespace='user-profile')),
    path('toko/', include(('toko.urls', 'toko'), namespace='toko')),
    path('makanan/', include(('makanan.urls', 'makanan'), namespace='makanan')),
    path('keranjang/', include(('keranjang.urls', 'keranjang'), namespace='keranjang')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('review/', include(('review.urls', 'review'), namespace='review')),
    path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
    ]

review/urls.py
from django.urls import path
from review.views import show_review, reply_review, create_review

appname = 'review'

urlpatterns = [
    path('<int:makanan_id>/', show_review, name='show_review'),
    path('create/<int:makanan_id>/', create_review, name='create_review'),
    path('reply/<int:review_id>/', reply_review, name='reply_review')
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from makanan.models import Makanan
from toko.models import Toko


class OrderGroup(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_harga = models.FloatField()

class Order(models.Model):
    # ENUM FOR ORDER STATUS
    class StatusPesanan(models.TextChoices):
        DIPESAN = "DIPESAN"
        DIPROSES = "DIPROSES"
        SELESAI = "SELESAI"
        DIBATALKAN = "DIBATALKAN"

    order_group = models.ForeignKey(OrderGroup, on_delete=models.CASCADE)
    makanan = models.ForeignKey(Makanan, on_delete=models.CASCADE)
    toko = models.ForeignKey(Toko, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    status = models.CharField(
        default = StatusPesanan.DIPESAN,
        max_length= 10,
        choices=StatusPesanan.choices
    )

order/views.py
from django.shortcuts import render
from keranjang.models import ItemKeranjang
from .models import Order, OrderGroup
from user_profile.models import Profile
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse
from toko.models import Toko
from makanan.models import Makanan
from django.views.decorators.csrf import csrf_exempt

def show_main_penjual(request, toko_id):
    toko = Toko.objects.get(pk=toko_id)
    orders = Order.objects.filter(toko=toko)

    pesanan_cnt = 0
    for order in orders:
        pesanan_cnt += 1

    context = {
        'orders': orders,
    }

    return render(request, "penjual.html", context)

def show_main_pembeli(request):
    orders = Order.objects.all()
    order_group = OrderGroup.objects.all()
    order_list = []

    for og in order_group:
        o = orders.filter(order_group = og)

        order_list.append({'pk': og.pk, 'total_harga': og.total_harga, 'orders': o, 'status': aggregat_status(o)})

    context = {
        'order_group': order_list,
    }
    print(order_list)

    return render(request, "pembeli.html", context)

def order_id_generator(og):
    orderID = og.user.username.upper()[:5] + og.toko.name.upper()[:5]  # ???
    date_added = og.date_added.split()
    date = date_added[0][:11]
    orderID += date.replace("-", "")
    checksum = 0
    for i in orderID:
        checksum += ord(i)

    orderID += (checksum % 10)
    return orderID

@csrf_exempt
def edit_status_penjual(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        order = Order.objects.get(pk=int(order_id))

        if (order.status == "DIBATALKAN"):
            return HttpResponse(400)

        order_status = request.POST.get('order_status')
        order.status = getattr(Order.StatusPesanan, order_status)
        order.save()

        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

@csrf_exempt
def edit_status_batal(request, og_id):
    order_group = OrderGroup.objects.get(pk=og_id)
    orders = Order.objects.filter(order_group=order_group)

    for order in orders:
        order.status = Order.StatusPesanan.DIBATALKAN
        order.save()

    return HttpResponse(status=200)


# HELPER FUNCTION
def aggregat_status(orders):
    statuses = []
    status = ""

    for order in orders:
        statuses.append(order.status)

    for s in statuses:
        if s == "DIBATALKAN":
            status = "DIBATALKAN"
            break
        elif s == "DIPESAN" or s == "DIPROSES":
            status = "DIPROSES"
            break
    else:
        status = "SELESAI"
    return status

order/templates/index.html
{% extends 'base.html' %}

{% block meta %}
    <title>Toko {{ user.profile.nama_lengkap }}</title>
{% endblock meta %}

{% block content %}

{% endblock content %}

order/templates/pembeli.html
{% extends 'base.html' %} {% block content %}

<div class="w-full min-h-screen flex">
  <div class="divider divider-horizontal"></div>
  <section class="basis-3/4 p-8">
    <div class="flex justify-between items-center mb-10">
      <h2 class="text-3xl font-bold">Order List</h2>
    </div>
    <section class="grid grid-cols-2 gap-10">
      <!-- start of ogcard -->
      {% for og in order_group %}
      <div
        id="og_card_{{og.pk}}"
        class="card h-fit bg-primary text-primary-content"
        value="{{o}}"
      >
        <div class="card-body">
          <div class="flex flex-row justify-between items-center">
            <h2 class="card-title text-xl pl-1">Order ID: {{ og.pk }}</h2>
            <h3 class="font-semibold mr-4 p-0">{{ og.user }}</h3>
          </div>
          {% for order in og.orders %}
          <!-- start of ordercard -->
          <section
            class="card h-fit bg-base-content text-primary-content border-2 border-primary-content"
            id="order_card_{{og.pk}}"
          >
            <div class="card-body">
              <h2 class="card-title text-2xl">{{ order.makanan.nama }}</h2>
              <div class="flex flex-row justify-between">
                <h3 class="text-neutral font-semibold">Toko {{ order.toko }}</h3>
                <h2 class="font-semibold pb-5">Jumlah: {{ order.quantity }}</h2>
              </div>
              {% if order.status == "SELESAI" %}
              <a
                href="{% url 'review:create_review' makanan_id=order.makanan.pk %}"
                class="btn bg-primary-content hover:scale-105"
                id="review_btn_{{order.pk}}"
                value="{{order.pk}}"
                onclick="allowReview(this)"
                >Review</a
              >
              {% endif %}
            </div>
          </section>
          <!-- end of ordercard -->
          {% endfor %}
        </div>
        <!-- end of ogcard -->
        <div class="flex justify-between items-center">
          <div class="flex flex-col">
            <div class="w-8 h-8 bg-base-100 rounded-tr-full"></div>
            <div class="w-8 h-8 bg-base-100 rounded-br-full"></div>
          </div>
          <div
            class="border-t-4 space-x-4 border-dashed border-base-100 flex-grow"
          ></div>
          <div class="flex flex-col">
            <div class="w-8 h-8 bg-base-100 rounded-tl-full"></div>
            <div class="w-8 h-8 bg-base-100 rounded-bl-full"></div>
          </div>
        </div>
        <div class="w-full p-8">
          <div class="flex flex-row justify-between font-bold">
            <h3>TOTAL</h3>
            <h3>Rp{{ og.total_harga }}</h3>
          </div>
          <div class="border-t-2 border-solid border-[#8a5500] my-2"></div>
          <div class="flex flex-row justify-between">
            <h3 class="font-bold">Status Pesanan:</h3>
            <h5 id="order_status" class="font-bold">{{og.status}}</h5>
          </div>
          <button
            type="button"
            class="btn w-full mt-8 py-2 px-4 border border-transparent text-sm font-medium rounded-lg text-white bg-red-600 hover:bg-red-500 outline-none"
            id="status_btn_{{og.pk}}"
            value="{{og.pk}}"
            onclick="batalkanPesanan(this)"
          >
            Batalkan Pesanan
          </button>
        </div>
      </div>
      {% endfor %}
    </section>
  </section>
</div>

<script>
  async function updateCard(el, status) { // el nya status_btn aja
    const ogCard = document.getElementById(`og_card_${el.value}`);
    const orderCards = document.querySelectorAll(`#og_card_${el.value} > div > section`)
    if (status === "DIBATALKAN") {
      ogCard.classList.remove("bg-primary");
      ogCard.classList.add("bg-primary/50");
      orderCards.forEach(orderCard => {
        orderCard.classList.remove("bg-base-content");
        orderCard.classList.add("bg-base-content/0");
      })
      el.classList.add("btn-disabled")
    }
    else if (status === "SELESAI") {
      el.classList.add("btn-disabled")
    }
  }

  {% for og in order_group %}
    updateCard(document.getElementById('status_btn_{{og.pk}}'), "{{og.status}}")
  {% endfor %}

  async function batalkanPesanan(el) {
    await fetch(
      '{% url "order:edit_status_batal" og_id=9999 %}'.replace(
        /9999/,
        el.value
      ),
      {
        method: "GET",
      }
    );

    updateCard(el, 'DIBATALKAN')
  }

  async function allowReview(el) {
    const reviewButton = document.getElementById(`review_btn_${el.value}`);
    if (el.value === "SELESAI") {
      reviewButton.style.display = "block";
      console.log("halo bg");
    } else {
      reviewButton.style.display = "none";
      console.log("kiw");
    }
  }
</script>
{% endblock content %}

order/templates/penjual.html
{% extends 'base.html' %} {% block content %}

<div class="w-full min-h-screen flex">
  <div class="divider divider-horizontal"></div>
  <section class="basis-3/4 p-8">
    <div class="flex justify-between items-center mb-10">
      <h2 class="text-3xl font-bold mb-5">Order</h2>
    </div>
    <section class="grid grid-cols-3 gap-10">
      {% for order in orders %}
      <div
        id="order_card_{{order.pk}}"
        class="card h-fit bg-primary text-primary-content"
      >
        <div class="card-body">
          <h2 class="card-title">
            {{ order.makanan.nama }} ({{ order.quantity }} pcs)
          </h2>
          <!-- <h3>{{ order.user }}</h3> -->
          <h3>Status:</h3>
          <h5 id="order_status_{{order.pk}}">{{order.status}}</h5>
          <button
            type="button"
            class="btn"
            id="status_btn_{{order.pk}}"
            value="{{order.pk}}"
            onclick="updatePesanan(this)"
          >
            Selesaikan Pesanan
          </button>
        </div>
      </div>
      {% endfor %}
    </section>
  </section>
</div>

<script>
  async function updateButton(el, status) {
    const orderCard = document.getElementById(`order_card_${el.value}`);
    if (status === "DIPESAN") {
      el.classList.remove("btn-disable")
      el.classList.remove("btn-accent")
      el.classList.add("btn-secondary")
      orderCard.classList.remove("bg-secondary")
      orderCard.classList.add("bg-primary")
      el.innerText = 'Proses Pesanan'
    } else if (status === "DIPROSES") {
      el.classList.remove("btn-secondary")
      el.classList.remove("btn-disable")
      el.classList.add("btn-primary");
      orderCard.classList.remove("bg-primary")
      orderCard.classList.add("bg-secondary")
      el.innerText = 'Selesaikan Pesanan'
    } else if (status === "SELESAI") {
      el.classList.remove("btn-primary")
      el.classList.remove("btn-secondary");
      el.classList.add("btn-disabled")
      orderCard.classList.remove("bg-primary")
      orderCard.classList.add("bg-secondary/50")

    } else {
      el.classList.remove("btn-primary")
      el.classList.remove("btn-secondary");
      el.classList.add("btn-disabled")
      orderCard.classList.add("bg-danger")
    }
  }

  {% for order in orders %}
    updateButton(document.getElementById('status_btn_{{order.pk}}'), "{{order.status}}")
  {% endfor %}

  async function updatePesanan(el) {
    const orderStatus = document.getElementById(`order_status_${el.value}`);
      if (orderStatus.innerText === "DIPESAN") {
        var data = new FormData();
        data.append("order_id", el.value);
        data.append("order_status", "DIPROSES");
        const res = await fetch("{% url 'order:edit_status_penjual' %}", {
          method: "POST",
          body: data,
        });
        orderStatus.innerText = "DIPROSES"
      } else {
        var data = new FormData();
        data.append("order_id", el.value);
        data.append("order_status", "SELESAI");
        const res = await fetch("{% url 'order:edit_status_penjual' %}", {
          method: "POST",
          body: data,
        });

        orderStatus.innerText = "SELESAI"
      }

    updateButton(el, orderStatus.innerText)
  }
</script>

{% endblock content %}