keranjang/urls.py
from django.urls import path
from keranjang import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.show_main, name='show-main'),
    path('get-item/', views.get_item, name='get-item'),
    path('add-item', views.add_item, name='add-item'),
    path('delete-item/<int:keranjang_id>', views.delete_item, name='delete-item'),
    path('checkout-cart/', views.checkout_cart, name='checkout-cart'),
    path('cek-stok/<int:keranjang_id>', views.cek_stok, name='cek-stok'),
    path('update-jumlah/<int:keranjang_id>', views.update_jumlah, name='update-jumlah')
]

main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index, name='index'),
]

pacil_food/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('main.urls', 'main'), namespace='main')),
    path('u/', include(('user_profile.urls', 'user_profile'), namespace='user-profile')),
    path('toko/', include(('toko.urls', 'toko'), namespace='toko')),
    path('makanan/', include(('makanan.urls', 'makanan'), namespace='makanan')),
    path('keranjang/', include(('keranjang.urls', 'keranjang'), namespace='keranjang')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('review/', include(('review.urls', 'review'), namespace='review')),
    path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
    ]

templates/base-non-navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.7.3/dist/full.min.css" rel="stylesheet" type="text/css"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block meta %} {% endblock meta %}
</head>

<body class="bg-base-100 min-w-screen min-h-screen flex flex-col" data-theme="coffee">
{% block base_content %}

{% endblock base_content %}
</body>
</html>

templates/base.html
{% extends 'base-non-navbar.html' %}

{% block base_content %}
    <div class="navbar fixed z-50 top-2 px-5">
        <div class="absolute w-full h-full py-2 rounded-full z-0">
            <div class="w-[calc(100%-40px)] h-full rounded-full bg-base-300"></div>
        </div>
        <div class="fixed w-full h-[10%] z-0 top-0 left-0 bg-gradient-to-b from-base-300/80 to-transparent">
        </div>
        <div class="w-full h-full py-1 px-3 rounded-full bg-primary/30 z-10">
            <div class="flex-1">
                <a class="btn btn-link" href="{% url 'main:index' %}">
                    {% load static %}
                    <img src="{% static 'brand-assets/logo.png' %}" class="block h-5" alt="">
                </a>
            </div>
            <div class="flex gap-5 mx-2">
                <div class="dropdown dropdown-end">
                    <a tabindex="0" role="button" class="btn btn-ghost btn-circle" href="{% url 'keranjang:show-main' %}">
                        <div class="indicator">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                                 stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                            </svg>
                            <span id="badge-jumlah" class="badge badge-sm indicator-item">8</span>
                        </div>
                    </a>
                    <div tabindex="0" class="mt-3 z-[1] card card-compact dropdown-content w-96 p-3 bg-base-100 shadow">
                        <div class="card-body max-h-1/2">
                            <div class="flex flex-col">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="dropdown dropdown-end">
                    <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
                        <div class="w-10 rounded-full">
                            <img alt="Tailwind CSS Navbar component"
                                 src="{{ user.profile.pfp_url }}"/>
                        </div>
                    </div>
                    <ul tabindex="0"
                        class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                        <li>
                            <a class="justify-between" href="{% url 'user_profile:profile' user.pk %}">
                                Profile
                                <span class="badge">New</span>
                            </a>
                        </li>
                        <li><a href="{% url 'user_profile:logout' %}">Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <main class="pt-20 grow">
        {% block content %}
        {% endblock content %}
        <dialog id="cart_limit_modal" class="modal">
            <div class="modal-box">
                <h3 class="font-bold text-lg">Hello!</h3>
                <p class="py-4">Press ESC key or click the button below to close</p>
                <div class="modal-action">
                    <form method="dialog">
                        <!-- if there is a button in form, it will close the modal -->
                        <button class="btn">Close</button>
                    </form>
                </div>
            </div>
        </dialog>
    </main>
    <footer class="mt-10 footer items-center p-6 bg-neutral text-neutral-content">
        <aside class="items-center grid-flow-col">
            {% load static %}
            <img src="{% static 'brand-assets/logo.png' %}" class="block h-5" alt="">
            <p>Copyright © 2024 - All right reserved</p>
        </aside>
        <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
            <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
                </svg>
            </a>
            <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
                </svg>
            </a>
            <a>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
                    <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
                </svg>
            </a>
        </nav>
    </footer>

    <script>
        async function refreshCart() {
            const data = await fetch("{% url 'keranjang:get-item' %}", {
                method: "GET"
            });
            const keranjang = await data.json()

            const badgeJml = document.getElementById('badge-jumlah')
            const jmlItem = document.getElementById("jumlah-item")


            badgeJml.innerText = `${keranjang.length}`

            const cartContainer = document.getElementById('cart-container')

            keranjang.forEach(item => {
                const card = document.createElement('div')
                const classesName = "card card-side bg-base-100 shadow-xl".split(" ")
                card.classList.add(classesName)
                card.innerHTML = `<figure class="p-3"><img src="https://daisyui.com/images/stock/photo-1635805737707-575885ab0820.jpg"
                                    alt="Movie"/></figure>
                                <div class="card-body">
                                    <h2 class="card-title"></h2>
                                    <p>Click the button to watch on Jetflix app.</p>
                                    <div class="card-actions justify-end">
                                        <button class="btn btn-primary">Watch</button>
                                    </div>
                                </div>`
                cartContainer.appendChild(card)
            })
        }

        refreshCart();

        async function addToCart(event) {
            var data = new FormData()

            data.append("makanan_id", event.value)

            const res = await fetch("{% url 'keranjang:add-item' %}", {
                method: "POST",
                body: data
            })

            await refreshCart()

            if (res.status === 400) {
                cart_limit_modal.showModal()
            }
        }
    </script>
{% endblock base_content %}